[OpenCL][unit tests] Fix opencl cpp unit tests (#13254)
* [OpenCL][unit tests] Fix opencl cpp unit tests

After some changes in Hexagon, the run of cpp opencl tests leads to the
following error:
```
pluggy.manager.PluginValidationError: unknown hook 'pytest_configure_node' in plugin <module 'tvm.contrib.hexagon.pytest_plugin'
```
Added `pytest_plugin` for OpenCL CPP tests for avoiding this error and
processing gtest arguments.

* Fix fail than gtest_args option was already added

* Move `gtest_args` deginition to the main testing plugin